// <auto-generated />
using System;
using LibraryManager.Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManager.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryManagerContext))]
    [Migration("20260125131951_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManager.Domain.Entities.Livre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Auteur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDeSortie")
                        .HasColumnType("datetime2");

                    b.Property<int>("NbPages")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatutLivre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Livres");
                });
#pragma warning restore 612, 618
        }
    }
}
